/*
 * Generated by classgen, version 1.5
 * 29.07.13 17:46
 */
package asttweaks;

import edu.tum.lua.ast.*;

public class FuncBody {

  private SyntaxNode parent;
  private ParList parlist;
  private Block block;

  public FuncBody (ParList parlist, Block block) {
    this.parlist = parlist;
    this.block = block;
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public String toString() {
    return "FuncBody";
  }

public NameList getArgs() {
	return parlist.namelist;
}

public boolean getVarArgs() {
	return parlist.varparlist;
}

public Block getBlock() {
	return block;
}


}