
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 30 19:27:52 CEST 2013
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int POW = 6;
  public static final int IN = 3;
  public static final int NUMBER = 10;
  public static final int SEMI = 7;
  public static final int VARIABLE = 11;
  public static final int EQ = 8;
  public static final int EOF = 0;
  public static final int ADD = 4;
  public static final int error = 1;
  public static final int MUL = 5;
  public static final int OUT = 2;
  public static final int LEQ = 9;
}

