/*
 * Generated by classgen, version 1.5
 * 31.07.13 15:23
 */

package edu.tum.lua.ast;

import location.Location;
import edu.tum.lua.ast.VisitorNode;

public abstract class SyntaxNode implements VisitorNode {
	
  private Location location;
  
  public Location getLocation() {
	  return location;
  }
  public void setLocation(Location location) {
	  this.location = location;
  }
	
  public abstract SyntaxNode getParent();
  public abstract void setParent(SyntaxNode parent);
}
