/*
 * Generated by classgen, version 1.5
 * 31.07.13 15:23
 */

package edu.tum.lua.ast;

import location.Location;
import edu.tum.lua.ast.VisitorNode;

public abstract class SyntaxNode implements VisitorNode {

	private Location marker;

	private Location start;

	private Location end;

	public Location getMarker() {
		return marker;
	}

	public void setMarker(Location location) {
		this.marker = location;
	}

	public Location getEnd() {
		return end;
	}

	public Location getStart() {
		return start;
	}

	public void setEnd(Location end) {
		this.end = end;
	}

	public void setStart(Location start) {
		this.start = start;
	}

	public abstract SyntaxNode getParent();

	public abstract void setParent(SyntaxNode parent);
}
