/* The following code was generated by JFlex 1.4.3 on 29.07.13 14:43 */


/**
*   JFlex Scanner
*/
package edu.tum.lua.parser;
import java_cup.runtime.Symbol;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 29.07.13 14:43 from the specification file
 * <tt>C:/Users/KB/workspace/compiler/Frontend/flex/Scanner.jflex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner, sym {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRINGSINGLE = 4;
  public static final int YYINITIAL = 0;
  public static final int STRINGDOUBLE = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\7\1\6\1\0\1\7\1\5\22\0\1\7\1\0\1\15"+
    "\1\54\1\0\1\52\1\0\1\16\1\55\1\14\1\47\1\46\1\42"+
    "\1\10\1\4\1\50\1\3\11\2\1\53\1\41\1\44\1\12\1\45"+
    "\2\0\32\1\1\11\1\60\1\13\1\51\1\1\1\0\1\22\1\37"+
    "\1\21\1\31\1\30\1\23\1\1\1\33\1\27\1\1\1\40\1\17"+
    "\1\1\1\25\1\20\1\35\1\1\1\34\1\36\1\26\1\24\1\1"+
    "\1\32\3\1\1\56\1\0\1\57\1\43\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\2\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\15\2\1\15\1\16"+
    "\1\1\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\1"+
    "\1\33\1\1\1\0\1\35\1\0\1\36\1\2\1\37"+
    "\11\2\1\40\1\41\2\2\1\42\3\2\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\3"+
    "\1\54\1\0\2\55\1\0\1\2\1\56\1\57\3\2"+
    "\1\60\1\61\3\2\1\62\4\2\1\0\4\2\1\63"+
    "\1\64\1\65\4\2\2\55\1\0\1\66\1\67\1\2"+
    "\1\70\1\2\1\71\2\2\1\72\2\0\1\55\1\2"+
    "\1\73\1\74\1\75\1\2\1\76";

  private static int [] zzUnpackAction() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\u0126\0\u0157"+
    "\0\u0188\0\u01b9\0\223\0\u01ea\0\223\0\223\0\223\0\223"+
    "\0\u021b\0\u024c\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372"+
    "\0\u03a3\0\u03d4\0\u0405\0\u0436\0\u0467\0\223\0\223\0\u0498"+
    "\0\u04c9\0\u04fa\0\223\0\223\0\223\0\223\0\223\0\223"+
    "\0\223\0\223\0\223\0\223\0\u052b\0\223\0\u055c\0\u058d"+
    "\0\u05be\0\u05ef\0\u0620\0\u0651\0\223\0\u0682\0\304\0\u06b3"+
    "\0\u06e4\0\u0715\0\u0746\0\u0777\0\u07a8\0\u07d9\0\u080a\0\u083b"+
    "\0\304\0\304\0\u086c\0\u089d\0\304\0\u08ce\0\u08ff\0\u0930"+
    "\0\223\0\223\0\223\0\223\0\223\0\223\0\223\0\223"+
    "\0\223\0\u05ef\0\223\0\u0961\0\u0992\0\223\0\u09c3\0\u09f4"+
    "\0\304\0\304\0\u0a25\0\u0a56\0\u0a87\0\304\0\304\0\u0ab8"+
    "\0\u0ae9\0\u0b1a\0\304\0\u0b4b\0\u0b7c\0\u0bad\0\u0bde\0\u0c0f"+
    "\0\u0c40\0\u0c71\0\u0ca2\0\u0cd3\0\304\0\304\0\u0d04\0\u0d35"+
    "\0\u0d66\0\u0d97\0\u0dc8\0\u0df9\0\u0e2a\0\u0e5b\0\304\0\304"+
    "\0\u0e8c\0\304\0\u0ebd\0\304\0\u0eee\0\u0f1f\0\304\0\u0e2a"+
    "\0\u0f50\0\u0961\0\u0f81\0\304\0\304\0\304\0\u0fb2\0\304";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\3\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\5"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\5\1\34\2\5\1\35\1\5\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\4\5\55\2\4"+
    "\6\55\1\56\42\55\1\57\5\60\2\4\7\60\1\56"+
    "\41\60\1\61\62\0\3\5\13\0\22\5\22\0\2\6"+
    "\1\62\60\0\1\62\60\0\1\63\61\0\3\11\61\0"+
    "\1\64\62\0\1\65\47\0\3\5\13\0\1\5\1\66"+
    "\20\5\21\0\3\5\13\0\15\5\1\67\4\5\21\0"+
    "\3\5\13\0\6\5\1\70\13\5\21\0\3\5\13\0"+
    "\1\5\1\71\1\5\1\72\1\5\1\73\14\5\21\0"+
    "\3\5\13\0\6\5\1\74\13\5\21\0\3\5\13\0"+
    "\1\5\1\75\6\5\1\76\11\5\21\0\3\5\13\0"+
    "\14\5\1\77\1\100\4\5\21\0\3\5\13\0\4\5"+
    "\1\101\1\5\1\102\13\5\21\0\3\5\13\0\1\103"+
    "\5\5\1\104\13\5\21\0\3\5\13\0\1\5\1\105"+
    "\20\5\21\0\3\5\13\0\14\5\1\106\5\5\21\0"+
    "\3\5\13\0\11\5\1\107\10\5\21\0\3\5\13\0"+
    "\15\5\1\110\4\5\32\0\1\111\60\0\1\112\60\0"+
    "\1\113\46\0\5\55\2\0\6\55\1\0\42\55\16\0"+
    "\1\114\7\0\1\115\1\116\5\0\1\117\23\0\1\120"+
    "\5\60\2\0\7\60\1\0\41\60\17\0\1\121\6\0"+
    "\1\115\1\116\5\0\1\117\23\0\1\120\2\0\2\122"+
    "\61\0\1\123\54\0\5\124\1\125\1\126\2\124\1\127"+
    "\47\124\1\0\3\5\13\0\2\5\1\130\17\5\21\0"+
    "\3\5\13\0\12\5\1\131\7\5\21\0\3\5\13\0"+
    "\15\5\1\132\4\5\21\0\3\5\13\0\1\133\21\5"+
    "\21\0\3\5\13\0\6\5\1\134\13\5\21\0\3\5"+
    "\13\0\7\5\1\135\12\5\21\0\3\5\13\0\7\5"+
    "\1\136\12\5\21\0\3\5\13\0\1\137\21\5\21\0"+
    "\3\5\13\0\11\5\1\140\10\5\21\0\3\5\13\0"+
    "\5\5\1\141\14\5\21\0\3\5\13\0\17\5\1\142"+
    "\2\5\21\0\3\5\13\0\12\5\1\143\7\5\21\0"+
    "\3\5\13\0\10\5\1\144\11\5\21\0\3\5\13\0"+
    "\7\5\1\145\6\5\1\146\3\5\21\0\3\5\13\0"+
    "\11\5\1\147\10\5\20\0\5\124\1\125\1\126\52\124"+
    "\6\0\1\126\52\0\5\124\1\125\1\126\2\124\1\150"+
    "\1\127\46\124\1\0\3\5\13\0\3\5\1\151\16\5"+
    "\21\0\3\5\13\0\17\5\1\152\2\5\21\0\3\5"+
    "\13\0\2\5\1\153\17\5\21\0\3\5\13\0\10\5"+
    "\1\154\11\5\21\0\3\5\13\0\6\5\1\155\13\5"+
    "\21\0\3\5\13\0\11\5\1\156\10\5\21\0\3\5"+
    "\13\0\11\5\1\157\10\5\21\0\3\5\13\0\1\160"+
    "\21\5\21\0\3\5\13\0\5\5\1\161\14\5\21\0"+
    "\3\5\13\0\11\5\1\162\10\5\21\0\3\5\13\0"+
    "\3\5\1\163\16\5\20\0\5\150\1\164\1\165\3\150"+
    "\1\124\1\166\1\124\32\150\1\124\5\150\1\124\3\150"+
    "\1\0\3\5\13\0\1\167\21\5\21\0\3\5\13\0"+
    "\11\5\1\170\10\5\21\0\3\5\13\0\7\5\1\171"+
    "\12\5\21\0\3\5\13\0\1\172\21\5\21\0\3\5"+
    "\13\0\10\5\1\173\11\5\21\0\3\5\13\0\11\5"+
    "\1\174\10\5\21\0\3\5\13\0\15\5\1\175\4\5"+
    "\21\0\3\5\13\0\3\5\1\176\16\5\21\0\3\5"+
    "\13\0\21\5\1\177\20\0\6\200\1\165\3\200\1\0"+
    "\1\201\1\0\32\200\1\0\5\200\1\0\15\200\1\0"+
    "\1\201\1\0\32\200\1\0\5\200\1\0\3\200\5\124"+
    "\1\125\1\126\3\124\1\166\1\202\45\124\1\0\3\5"+
    "\13\0\10\5\1\203\11\5\21\0\3\5\13\0\4\5"+
    "\1\204\15\5\21\0\3\5\13\0\6\5\1\205\13\5"+
    "\21\0\3\5\13\0\7\5\1\206\12\5\32\0\1\201"+
    "\1\126\46\0\3\5\13\0\1\5\1\207\20\5\21\0"+
    "\3\5\13\0\6\5\1\210\13\5\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4067];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\6\1\1\11\1\1\4\11\15\1\2\11"+
    "\3\1\12\11\1\1\1\11\3\1\1\0\1\1\1\0"+
    "\1\11\23\1\11\11\1\1\1\11\1\0\1\1\1\11"+
    "\1\0\20\1\1\0\15\1\1\0\11\1\2\0\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

  StringBuffer string = new StringBuffer();

  private Symbol symbol(int sym) {
    return new Symbol(sym, yyline+1, yycolumn+1);
  }
  
  private Symbol symbol(int sym, Object val) {
    return new Symbol(sym, yyline+1, yycolumn+1, val);
  }
  
  private void error(String message) {
    System.out.println("Error at line "+(yyline+1)+", column "+(yycolumn+1)+" : "+message);
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 134) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 45: 
          { /* ignore */
          }
        case 63: break;
        case 60: 
          { return symbol(RETURN);
          }
        case 64: break;
        case 29: 
          { return symbol(CONCAT);
          }
        case 65: break;
        case 2: 
          { return symbol(ID, yytext());
          }
        case 66: break;
        case 18: 
          { return symbol(MUL);
          }
        case 67: break;
        case 59: 
          { return symbol(ELSEIF);
          }
        case 68: break;
        case 4: 
          { return symbol(DOT);
          }
        case 69: break;
        case 40: 
          { string.append("\t");
          }
        case 70: break;
        case 7: 
          { return symbol(LBRACK);
          }
        case 71: break;
        case 36: 
          { return symbol(LEQ);
          }
        case 72: break;
        case 52: 
          { return symbol(TRUE);
          }
        case 73: break;
        case 14: 
          { return symbol(COM);
          }
        case 74: break;
        case 55: 
          { return symbol(FALSE);
          }
        case 75: break;
        case 24: 
          { return symbol(LPAREN);
          }
        case 76: break;
        case 16: 
          { return symbol(GR);
          }
        case 77: break;
        case 53: 
          { return symbol(ELSE);
          }
        case 78: break;
        case 42: 
          { string.append("\\");
          }
        case 79: break;
        case 17: 
          { return symbol(ADD);
          }
        case 80: break;
        case 50: 
          { return symbol(END);
          }
        case 81: break;
        case 51: 
          { return symbol(THEN);
          }
        case 82: break;
        case 41: 
          { string.append("\r");
          }
        case 83: break;
        case 34: 
          { return symbol(DO);
          }
        case 84: break;
        case 48: 
          { return symbol(NOT);
          }
        case 85: break;
        case 46: 
          { return symbol(AND);
          }
        case 86: break;
        case 8: 
          { return symbol(ASM);
          }
        case 87: break;
        case 19: 
          { return symbol(DIV);
          }
        case 88: break;
        case 32: 
          { return symbol(IF);
          }
        case 89: break;
        case 38: 
          { string.append("\"");
          }
        case 90: break;
        case 13: 
          { return symbol(SEMI);
          }
        case 91: break;
        case 20: 
          { return symbol(POW);
          }
        case 92: break;
        case 62: 
          { return symbol(FUNC);
          }
        case 93: break;
        case 21: 
          { return symbol(MOD);
          }
        case 94: break;
        case 43: 
          { string.append("\'");
          }
        case 95: break;
        case 31: 
          { return symbol(OR);
          }
        case 96: break;
        case 33: 
          { return symbol(IN);
          }
        case 97: break;
        case 30: 
          { return symbol(EQ);
          }
        case 98: break;
        case 37: 
          { return symbol(GEQ);
          }
        case 99: break;
        case 6: 
          { return symbol(SUB);
          }
        case 100: break;
        case 22: 
          { return symbol(DDOT);
          }
        case 101: break;
        case 28: 
          { yybegin(YYINITIAL);
					  return symbol(TEXT,
					  string.toString());
          }
        case 102: break;
        case 25: 
          { return symbol(LCURL);
          }
        case 103: break;
        case 11: 
          { string.setLength(0); yybegin(STRINGDOUBLE);
          }
        case 104: break;
        case 26: 
          { return symbol(RCURL);
          }
        case 105: break;
        case 35: 
          { return symbol(NEQ);
          }
        case 106: break;
        case 9: 
          { return symbol(RBRACK);
          }
        case 107: break;
        case 61: 
          { return symbol(REPEAT);
          }
        case 108: break;
        case 44: 
          { return symbol(PARAMS);
          }
        case 109: break;
        case 39: 
          { string.append("\n");
          }
        case 110: break;
        case 3: 
          { return symbol(NUMBER, new Double(Double.parseDouble(yytext())));
          }
        case 111: break;
        case 1: 
          { /* throw new Error("Illegal character <"+ yytext()+">");*/
		    error("Illegal character <"+ yytext()+">");
          }
        case 112: break;
        case 5: 
          { return symbol(WS);
          }
        case 113: break;
        case 10: 
          { return symbol(RPAREN);
          }
        case 114: break;
        case 54: 
          { return symbol(LOCAL);
          }
        case 115: break;
        case 12: 
          { string.setLength(0); yybegin(STRINGSINGLE);
          }
        case 116: break;
        case 23: 
          { return symbol(LENGTH);
          }
        case 117: break;
        case 15: 
          { return symbol(LE);
          }
        case 118: break;
        case 58: 
          { return symbol(BREAK);
          }
        case 119: break;
        case 47: 
          { return symbol(FOR);
          }
        case 120: break;
        case 57: 
          { return symbol(WHILE);
          }
        case 121: break;
        case 49: 
          { return symbol(NIL);
          }
        case 122: break;
        case 56: 
          { return symbol(UNTIL);
          }
        case 123: break;
        case 27: 
          { string.append( yytext() );
          }
        case 124: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
