
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 26 14:43:31 CEST 2013
//----------------------------------------------------

package edu.tum.lua.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int POW = 29;
  public static final int CONCAT = 30;
  public static final int SEMI = 47;
  public static final int LPAREN = 41;
  public static final int REPEAT = 12;
  public static final int FOR = 10;
  public static final int RPAREN = 42;
  public static final int LCURL = 45;
  public static final int NOT = 39;
  public static final int AND = 37;
  public static final int ELSEIF = 17;
  public static final int NIL = 20;
  public static final int OR = 38;
  public static final int IN = 11;
  public static final int DDOT = 4;
  public static final int DIV = 27;
  public static final int GEQ = 36;
  public static final int UNTIL = 13;
  public static final int IF = 14;
  public static final int ID = 51;
  public static final int DOT = 3;
  public static final int LE = 34;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int TRUE = 22;
  public static final int error = 1;
  public static final int MUL = 25;
  public static final int ADD = 24;
  public static final int ASM = 2;
  public static final int NUMBER = 50;
  public static final int MOD = 28;
  public static final int NEQ = 33;
  public static final int BREAK = 19;
  public static final int EQ = 31;
  public static final int PARAMS = 23;
  public static final int COM = 48;
  public static final int LBRACK = 43;
  public static final int RCURL = 46;
  public static final int ELSE = 16;
  public static final int WS = 49;
  public static final int FUNC = 6;
  public static final int RBRACK = 44;
  public static final int WHILE = 9;
  public static final int THEN = 15;
  public static final int LEQ = 32;
  public static final int END = 7;
  public static final int LOCAL = 5;
  public static final int TEXT = 52;
  public static final int FALSE = 21;
  public static final int SUB = 26;
  public static final int GR = 35;
  public static final int LENGTH = 40;
  public static final int DO = 8;
}

