/*
 * Generated by classgen, version 1.5
 * 23.07.13 15:35
 */
package edu.tum.lua.ast;

public class ArgsTableConst extends Args {

  public FieldList fieldlist;

  public ArgsTableConst (FieldList fieldlist) {
    this.fieldlist = fieldlist;
    if (fieldlist != null) fieldlist.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (fieldlist != null) fieldlist.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (fieldlist != null) fieldlist.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (fieldlist != null) fieldlist.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("ArgsTableConst(\n");
      if (fieldlist != null)
        buffer.append(fieldlist.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [ArgsTableConst]");
    return buffer.toString();
  }
}
