/*
 * Generated by classgen, version 1.5
 * 31.07.13 15:50
 */
package edu.tum.lua.ast;

public class BooleanExp extends Exp {

  public boolean value;

  public BooleanExp (boolean value) {
    this.value = value;
  }

  @Override
public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  @Override
public void childrenAccept(Visitor visitor) {
  }

  @Override
public void traverseTopDown(Visitor visitor) {
    accept(visitor);
  }

  @Override
public void traverseBottomUp(Visitor visitor) {
    accept(visitor);
  }

  @Override
public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("BooleanExp(\n");
    buffer.append("  "+tab+value);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [BooleanExp]");
    return buffer.toString();
  }
}
