/*
 * Generated by classgen, version 1.5
 * 23.07.13 15:35
 */
package edu.tum.lua.ast;

public class Dots extends Exp {

  public String dots;

  public Dots (String dots) {
    this.dots = dots;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Dots(\n");
    buffer.append("  "+tab+dots);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Dots]");
    return buffer.toString();
  }
}
