/*
 * Generated by classgen, version 1.5
 * 31.07.13 15:50
 */
package edu.tum.lua.ast;

import java.util.Enumeration;
import java.util.Vector;

public class ExpList extends SyntaxNode {

	private final Vector<Exp> items;
	private SyntaxNode parent;

	public ExpList() {
		items = new Vector<>();
	}

	public ExpList(Exp anItem) {
		this();
		append(anItem);
	}

	public ExpList append(Exp anItem) {
		if (anItem == null)
			return this;
		anItem.setParent(this);
		items.addElement(anItem);
		return this;
	}

	public Enumeration<Exp> elements() {
		return items.elements();
	}

	public Exp elementAt(int index) {
		return items.elementAt(index);
	}

	public void setElementAt(Exp item, int index) {
		item.setParent(this);
		items.setElementAt(item, index);
	}

	public void insertElementAt(Exp item, int index) {
		item.setParent(this);
		items.insertElementAt(item, index);
	}

	public void removeElementAt(int index) {
		items.removeElementAt(index);
	}

	public int size() {
		return items.size();
	}

	public boolean isEmpty() {
		return items.isEmpty();
	}

	public boolean contains(Exp item) {
		int size = items.size();
		for (int i = 0; i < size; i++)
			if (item.equals(items.elementAt(i)))
				return true;
		return false;
	}

	public int indexOf(Exp item) {
		return items.indexOf(item);
	}

	@Override
	public String toString() {
		return toString("");
	}

	public String toString(String tab) {
		StringBuffer buffer = new StringBuffer();
		buffer.append(tab);
		buffer.append("ExpList (\n");
		int size = items.size();
		for (int i = 0; i < size; i++) {
			buffer.append(items.elementAt(i).toString("  " + tab));
			buffer.append("\n");
		}
		buffer.append(tab);
		buffer.append(") [ExpList]");
		return buffer.toString();
	}

	@Override
	public SyntaxNode getParent() {
		return parent;
	}

	@Override
	public void setParent(SyntaxNode parent) {
		this.parent = parent;
	}

	@Override
	public void accept(Visitor visitor) {
		visitor.visit(this);
	}

	@Override
	public void childrenAccept(Visitor visitor) {
		for (int i = 0; i < size(); i++)
			if (elementAt(i) != null)
				elementAt(i).accept(visitor);
	}

	@Override
	public void traverseTopDown(Visitor visitor) {
		this.accept(visitor);
		for (int i = 0; i < size(); i++)
			if (elementAt(i) != null)
				elementAt(i).traverseTopDown(visitor);
	}

	@Override
	public void traverseBottomUp(Visitor visitor) {
		for (int i = 0; i < size(); i++)
			if (elementAt(i) != null)
				elementAt(i).traverseBottomUp(visitor);
		this.accept(visitor);
	}

}
