/*
 * Generated by classgen, version 1.5
 * 26.07.13 16:53
 */
package edu.tum.lua.ast;

public class Function implements SyntaxNode {

  private SyntaxNode parent;
  public FuncBody funcbody;

  public Function (FuncBody funcbody) {
    this.funcbody = funcbody;
    if (funcbody != null) funcbody.setParent(this);
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (funcbody != null) funcbody.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (funcbody != null) funcbody.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (funcbody != null) funcbody.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString() {
    return toString("");
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Function(\n");
      if (funcbody != null)
        buffer.append(funcbody.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Function]");
    return buffer.toString();
  }
}
