/*
 * Generated by classgen, version 1.5
 * 29.07.13 14:43
 */
package edu.tum.lua.ast;

public class FunctionDef extends Stat {

  public FuncName funcname;
  public FuncBody funcbody;

  public FunctionDef (FuncName funcname, FuncBody funcbody) {
    this.funcname = funcname;
    if (funcname != null) funcname.setParent(this);
    this.funcbody = funcbody;
    if (funcbody != null) funcbody.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (funcname != null) funcname.accept(visitor);
    if (funcbody != null) funcbody.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (funcname != null) funcname.traverseTopDown(visitor);
    if (funcbody != null) funcbody.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (funcname != null) funcname.traverseBottomUp(visitor);
    if (funcbody != null) funcbody.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("FunctionDef(\n");
      if (funcname != null)
        buffer.append(funcname.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (funcbody != null)
        buffer.append(funcbody.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [FunctionDef]");
    return buffer.toString();
  }
}
