/*
 * Generated by classgen, version 1.5
 * 29.07.13 14:43
 */
package edu.tum.lua.ast;

public class LocalFuncDef extends Stat {

  public Name name;
  public FuncBody funcbody;

  public LocalFuncDef (Name name, FuncBody funcbody) {
    this.name = name;
    if (name != null) name.setParent(this);
    this.funcbody = funcbody;
    if (funcbody != null) funcbody.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (name != null) name.accept(visitor);
    if (funcbody != null) funcbody.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (name != null) name.traverseTopDown(visitor);
    if (funcbody != null) funcbody.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (name != null) name.traverseBottomUp(visitor);
    if (funcbody != null) funcbody.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("LocalFuncDef(\n");
      if (name != null)
        buffer.append(name.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (funcbody != null)
        buffer.append(funcbody.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [LocalFuncDef]");
    return buffer.toString();
  }
}
