/*
 * Generated by classgen, version 1.5
 * 23.07.13 15:35
 */
package edu.tum.lua.ast;

public class Number extends Exp {

  public double number;

  public Number (double number) {
    this.number = number;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Number(\n");
    buffer.append("  "+tab+number);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Number]");
    return buffer.toString();
  }
}
