/*
 * Generated by classgen, version 1.5
 * 31.07.13 15:50
 */
package edu.tum.lua.ast;

public interface Op {

  public final static int ADD = 0;
  public final static int SUB = 1;
  public final static int MUL = 2;
  public final static int DIV = 3;
  public final static int POW = 4;
  public final static int MOD = 5;
  public final static int CONCAT = 6;
  public final static int LT = 7;
  public final static int LE = 8;
  public final static int GT = 9;
  public final static int GE = 10;
  public final static int EQ = 11;
  public final static int NEQ = 12;
  public final static int AND = 13;
  public final static int OR = 14;
  public final static int UNM = 15;
  public final static int NOT = 16;
  public final static int LEN = 17;

}
