/*
 * Generated by classgen, version 1.5
 * 26.07.13 16:53
 */
package edu.tum.lua.ast;

public class ParList implements SyntaxNode {

  private SyntaxNode parent;
  public NameList namelist;
  public Boolean varparlist;

  public ParList (NameList namelist, Boolean varparlist) {
    this.namelist = namelist;
    if (namelist != null) namelist.setParent(this);
    this.varparlist = varparlist;
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (namelist != null) namelist.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (namelist != null) namelist.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (namelist != null) namelist.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString() {
    return toString("");
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("ParList(\n");
      if (namelist != null)
        buffer.append(namelist.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append("  "+tab+varparlist);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [ParList]");
    return buffer.toString();
  }
}
