/*
 * Generated by classgen, version 1.5
<<<<<<< HEAD
 * 23.07.13 15:35
=======
 * 24.07.13 15:58
>>>>>>> Intermediate
 */
package edu.tum.lua.ast;

public class PrefixExpFuncCall extends PrefixExp {

  public FunctionCall call;

  public PrefixExpFuncCall (FunctionCall call) {
    this.call = call;
    if (call != null) call.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (call != null) call.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (call != null) call.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (call != null) call.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("PrefixExpFuncCall(\n");
      if (call != null)
        buffer.append(call.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [PrefixExpFuncCall]");
    return buffer.toString();
  }
}
