/*
 * Generated by classgen, version 1.5
 * 23.07.13 15:35
 */

package edu.tum.lua.ast;

public interface SyntaxNode extends VisitorNode {
  public SyntaxNode getParent();
  public void setParent(SyntaxNode parent);
}
