/*
 * Generated by classgen, version 1.5
 * 26.07.13 10:01
 */

package edu.tum.lua.ast;

public interface SyntaxNode extends VisitorNode {
  public SyntaxNode getParent();
  public void setParent(SyntaxNode parent);
}
