/*
 * Generated by classgen, version 1.5
 * 23.07.13 15:35
 */
package edu.tum.lua.ast;

public class TextExp extends Exp {

  public Text text;

  public TextExp (Text text) {
    this.text = text;
    if (text != null) text.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (text != null) text.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (text != null) text.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (text != null) text.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("TextExp(\n");
      if (text != null)
        buffer.append(text.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [TextExp]");
    return buffer.toString();
  }
}
