/*
 * Generated by classgen, version 1.5
 * 31.07.13 15:50
 */

package edu.tum.lua.ast;

public interface VisitorNode {
  public void accept(Visitor visitor);

  public void childrenAccept(Visitor visitor);
  public void traverseBottomUp(Visitor visitor);
  public void traverseTopDown(Visitor visitor);
}
