/*
 * Generated by classgen, version 1.5
 * 30.05.13 19:22
 */
package node;

public class Exp implements SyntaxNode {

  private SyntaxNode parent;
  public String var;
  public int exp;

  public Exp (String var, int exp) {
    this.var = var;
    this.exp = exp;
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    accept(visitor);
  }

  public String toString() {
    return toString("");
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Exp(\n");
    buffer.append("  "+tab+var);
    buffer.append("\n");
    buffer.append("  "+tab+exp);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Exp]");
    return buffer.toString();
  }
}
