/*
 * Generated by classgen, version 1.5
 * 30.05.13 19:22
 */
package node;

public class Polynom implements SyntaxNode {

  private SyntaxNode parent;
  public String var;
  public PolyPart polypart;

  public Polynom (String var, PolyPart polypart) {
    this.var = var;
    this.polypart = polypart;
    if (polypart != null) polypart.setParent(this);
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (polypart != null) polypart.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (polypart != null) polypart.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (polypart != null) polypart.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString() {
    return toString("");
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Polynom(\n");
    buffer.append("  "+tab+var);
    buffer.append("\n");
      if (polypart != null)
        buffer.append(polypart.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Polynom]");
    return buffer.toString();
  }
}
