/*
 * Generated by classgen, version 1.5
 * 30.05.13 19:22
 */

package node;

public interface SyntaxNode extends VisitorNode {
  public SyntaxNode getParent();
  public void setParent(SyntaxNode parent);
}
