/*
 * Generated by classgen, version 1.5
 * 30.05.13 19:22
 */
package node;

public abstract class VisitorAdaptor implements Visitor {

  public void visit(Prog prog) { visit(); }
  public void visit(Output output) { visit(); }
  public void visit(Constraint constraint) { visit(); }
  public void visit(Input input) { visit(); }
  public void visit(Term term) { visit(); }
  public void visit(PolyPart polyPart) { visit(); }
  public void visit(ExpSeq expSeq) { visit(); }
  public void visit(Exp exp) { visit(); }
  public void visit(Polynom polynom) { visit(); }

  public void visit() { }

}
