/*
 * Generated by classgen, version 1.5
 * 30.05.13 19:22
 */
package node;

public interface Visitor {

  public void visit(Prog prog);
  public void visit(Output output);
  public void visit(Constraint constraint);
  public void visit(Input input);
  public void visit(Term term);
  public void visit(PolyPart polyPart);
  public void visit(ExpSeq expSeq);
  public void visit(Exp exp);
  public void visit(Polynom polynom);

}
