/*
 * Generated by classgen, version 1.5
 * 29.07.13 17:46
 */
package edu.tum.juna.ast;


public class FuncBody extends SyntaxNode {

	private SyntaxNode parent;
	private final ParList parlist;
	private final Block block;

	public FuncBody(ParList parlist, Block block) {
		this.parlist = parlist;
		this.block = block;
	}

	@Override
	public SyntaxNode getParent() {
		return parent;
	}

	@Override
	public void setParent(SyntaxNode parent) {
		this.parent = parent;
	}

	@Override
	public String toString() {
		return "FuncBody";
	}

	public NameList getArgs() {
		return parlist.namelist;
	}

	public boolean getVarArgs() {
		return parlist.varparlist;
	}

	public Block getBlock() {
		return block;
	}

	@Override
	public void accept(Visitor visitor) {
		throw new RuntimeException("Should not be here!");

	}

	@Override
	public void childrenAccept(Visitor visitor) {
		throw new RuntimeException("Should not be here!");

	}

	@Override
	public void traverseBottomUp(Visitor visitor) {
		throw new RuntimeException("Should not be here!");

	}

	@Override
	public void traverseTopDown(Visitor visitor) {
		throw new RuntimeException("Should not be here!");

	}

}